---
- name: Upgrade System
  apt:
    upgrade: dist 
    update_cache: yes
#Add cerbot repository in dep list
- name: Add certbot repository
  apt_repository:
   repo: 'ppa:certbot/certbot'

- name: Install Certbot's Nginx package
  apt:
   name: python-certbot-nginx
   state: present
   
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ item.domain }}/cert.pem
  register: letsencrypt_cert
  with_items: "{{ domains }}"

  #Stop services
- name: Stop services to allow certbot to generate a cert.
  become: true
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
          -  "{{ certbot_impacted_services }}"

- name: Generate new certificate if one doesn't exist.
  become: true
  shell: "certbot --standalone --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.domain }}"
  with_items: "{{ letsencrypt_cert.results }}"
  #when: item.stat.exists == False

  #Start services
- name: Start services after cert has been generated.
  become: true
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ certbot_impacted_services }}"