---
- name: Update apt packages
  become: true
  apt:
    upgrade: yes

- name: Install openvpn & dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - openssl
 #https://docs.ansible.com/ansible/latest/modules/get_url_module.html?highlight=get_url 
- name: Download eazy-rsa
  become: yes
  get_url: 
    dest: /home/{{ user }}/eazy-rsa/eazy-rsa.tgz
    force: yes
    url: "{{ EASY_RSA_Link }}"

# https://docs.ansible.com/ansible/latest/modules/unarchive_module.html
- name: Extract eazy-rsa
  become: yes
  unarchive:
    src: /home/{{ user }}/eazy-rsa/eazy-rsa.tgz
    dest: /home/{{ user }}/eazy-rsa


- name: Remove easy-rsa archive
  become: yes
  file:
    path: /home/{{ user }}/eazy-rsa/eazy-rsa.tgz
    state: absent

- name: Create easy-rsa var file
  become: yes
  copy:
    src: /home/{{ user }}/eazy-rsa/vars.example
    dest: /home/{{ user }}/eazy-rsa/vars

  #Custom easy-rsa configuration
- name: Customize CA variable configuration
  lineinfile:
    dest: /home/{{ user }}/eazy-rsa/vars
    regexp: "^{{ item.property | regex_escape() }}="
    line: "{{ item.property }}={{ item.value }}"
  with_items:
    - { property: 'export KEY_NAME', value: "{{ EASYRSA_REQ_NAME }}" }
    - { property: 'export KEY_COUNTRY', value: "{{ EASYRSA_REQ_COUNTRY }}" }
    - { property: 'export KEY_PROVINCE', value: "{{ EASYRSA_REQ_PROVINCE }}" }
    - { property: 'export KEY_CITY', value: "{{ EASYRSA_REQ_CITY }}" }
    - { property: 'export KEY_ORG', value: "{{ EASYRSA_REQ_ORG }}" }
    - { property: 'export KEY_EMAIL', value: "{{ EASYRSA_REQ_EMAIL }}" }
    - { property: 'export KEY_OU', value: "{{ EASYRSA_REQ_OU }}" }
    - { property: 'export KEY_DIR', value: '{{ ansible_env.HOME }}/openvpn-ca/keys' }


#Start openvpn servce
#- name: Start openvpn service
#  become: true
#  service:
#    name: openvpn
#    state: started
#    enabled: yes
...

