---
- name: Install
  become: yes
  apt: name=nginx state=latest

- name: Start
  become: yes
  service: name = nginx state = started enabled = true

- name: Delete default configuration
  become: yes
  file: path = /etc/nginx/sites-enabled/default state = absent
  notify: nginx reload

- name: COnfiguration web site
  include: site.yml
  with_items: domains
...