---
- name: Install web server
  hosts: webserver
  become: yes
  vars:
    user: ngnix_user
    domains:
      - domain: test.florianbonniec.com
        git_repo: https://github.com/Florian22/cheap_website.git
  #remote_user: ubuntu

  #Roles are execute before tasks always
  roles:
    #- utils
    #- system_user
    #- nginx
    #- cerbot
    - openvpn
...